include("edit_file_global.jl")
simulations = []
include("edit_file_vegf.jl")
push!(simulations,rate_constant_update_array)
include("edit_file_vegf_vi.jl")
push!(simulations,rate_constant_update_array)
include("edit_file_tgfb_vi.jl")
push!(simulations,rate_constant_update_array)
include("edit_file_tgfb_vegf.jl")
push!(simulations,rate_constant_update_array)
include("edit_file_vegf_vi.jl")
push!(simulations,rate_constant_update_array)
include("edit_file_tgfb_vegf_vi.jl")
push!(simulations,rate_constant_update_array)

